POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Vagner Nerves",
  "email": "vagnernervessantosoutro@gmail.com",
  "referrer": "5e7f8ebb-aac6-4254-a9cb-8c6fb1537622"
}

####

GET http://localhost:3333/invites/5e7f8ebb-aac6-4254-a9cb-8c6fb1537622

####

GET http://localhost:3333/subscribers/5e7f8ebb-aac6-4254-a9cb-8c6fb1537622/ranking/clicks

####

GET http://localhost:3333/subscribers/5e7f8ebb-aac6-4254-a9cb-8c6fb1537622/ranking/count

####

GET http://localhost:3333/subscribers/5e7f8ebb-aac6-4254-a9cb-8c6fb1537622/ranking/position